---
swagger: "2.0"
info:
  description: "Simple server for upgrade files hosting"
  version: "1.0.0"
  title: "Upgrade server"
basePath: "/upgrade"
schemes:
- "http"
produces:
- "application/json"
paths:
  /files:
    get:
      tags:
      - "files_management"
      summary: "Gets files list."
      description: "Returns a list containing all files."
      operationId: "files_get"
      parameters: []
      responses:
        200:
          description: "A list of files"
          schema:
            $ref: "#/definitions/files"
      x-swagger-router-controller: "upgrade_server.controllers.files_management_controller"
  /files/{filename}:
    get:
      tags:
      - "files_management"
      summary: "Gets a file binary"
      description: "Returns a single file by filename"
      operationId: "files_filename_get"
      parameters:
      - name: "filename"
        in: "path"
        description: "The filename"
        required: true
        type: "string"
      responses:
        200:
          description: "A file binary"
          schema:
            type: "file"
        404:
          description: "The file does not exists."
      x-swagger-router-controller: "upgrade_server.controllers.files_management_controller"
  /version:
    get:
      tags:
      - "service_api"
      summary: "Gets api version"
      description: "Returns a version of the api."
      operationId: "version_get"
      parameters: []
      responses:
        200:
          description: "A version of api."
          schema:
            $ref: "#/definitions/version"
      x-swagger-router-controller: "upgrade_server.controllers.service_api_controller"
definitions:
  files:
    type: "array"
    items:
      $ref: "#/definitions/file"
  file:
    type: "object"
    required:
    - "file_name"
    - "file_size"
    properties:
      file_name:
        type: "string"
        example: "my_little_kitty.bin"
      file_size:
        type: "integer"
        example: 15
  version:
    required:
    - "version"
    properties:
      version:
        type: "string"
        example: "1.0"
    example:
      version: "1.0"
